GET {{url}}/without-api-controller-attribute/with-parameter?id=invalid

###

POST {{url}}/without-api-controller-attribute/with-parameter
Content-Type: application/json

invalid

###

PUT {{url}}/without-api-controller-attribute/with-parameter/invalid
Content-Type: application/json

{"id":42}

###

PUT {{url}}/without-api-controller-attribute/with-parameter/42
Content-Type: application/json

invalid

###

DELETE {{url}}/without-api-controller-attribute/with-parameter/invalid

###
